// Firebase client settings for each platform, read from the environment (see
// Environment and .env.example) instead of being written into the source.
//
// This file was first generated by the FlutterFire CLI. Running
// `flutterfire configure` again rewrites it with literal values: restore this
// version with `git checkout lib/firebase_options.dart` and put any new values
// in .env instead.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'infrastructure/core/environment.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Environment.firebaseAndroidApiKey,
    appId: Environment.firebaseAndroidAppId,
    messagingSenderId: Environment.firebaseMessagingSenderId,
    projectId: Environment.firebaseProjectId,
    storageBucket: Environment.firebaseStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Environment.firebaseAppleApiKey,
    appId: Environment.firebaseAppleAppId,
    messagingSenderId: Environment.firebaseMessagingSenderId,
    projectId: Environment.firebaseProjectId,
    storageBucket: Environment.firebaseStorageBucket,
    androidClientId: Environment.googleAndroidClientId,
    iosClientId: Environment.googleIosClientId,
    iosBundleId: Environment.firebaseAppleBundleId,
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Environment.firebaseWebApiKey,
    appId: Environment.firebaseWebAppId,
    messagingSenderId: Environment.firebaseMessagingSenderId,
    projectId: Environment.firebaseProjectId,
    authDomain: Environment.firebaseWebAuthDomain,
    storageBucket: Environment.firebaseStorageBucket,
    measurementId: Environment.firebaseWebMeasurementId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Environment.firebaseAppleApiKey,
    appId: Environment.firebaseAppleAppId,
    messagingSenderId: Environment.firebaseMessagingSenderId,
    projectId: Environment.firebaseProjectId,
    storageBucket: Environment.firebaseStorageBucket,
    iosBundleId: Environment.firebaseAppleBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Environment.firebaseWebApiKey,
    appId: Environment.firebaseWindowsAppId,
    messagingSenderId: Environment.firebaseMessagingSenderId,
    projectId: Environment.firebaseProjectId,
    authDomain: Environment.firebaseWebAuthDomain,
    storageBucket: Environment.firebaseStorageBucket,
    measurementId: Environment.firebaseWindowsMeasurementId,
  );
}
